# Generated by Django 5.2.1 on 2025-05-18 15:59

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code, e.g. +1234567890', max_length=20, null=True, validators=[users.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter username without @ and special characters', max_length=15, null=True, validators=[users.models.validate_twitter_handle]),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
