# Generated by Django 5.2.1 on 2025-05-18 16:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter username without @. Allowed characters: letters, numbers, and underscores.', max_length=15, null=True, validators=[users.models.validate_twitter_handle]),
        ),
    ]
